### ISSUE TITLE
Fix API_VERSION

### ISSUE THREAD

**Issue by tabaktoni** [starknet-io/types-js#20]
### From @PhilippeR26
_I received an interesting question : why ApiVersion and SpecVersion do not have the same type? Why an object on one side and a string on the other side?
https://github.com/starknet-io/types-js/blob/76a31d51b7a6254b28f75cab3ace272dfea72e25/src/wallet-api/components.ts#L22-L26 
https://github.com/starknet-io/types-js/blob/76a31d51b7a6254b28f75cab3ace272dfea72e25/src/wallet-api/components.ts#L144-L149
Honestly, the question is legit._

### From @tabaktoni 
1. Question ?
_The second question I have here, and I can't remember what it is, is how developers correlate API_VERSION and SPEC_VERSION.

 API_VERSION is the version of the API provided by the wallet (internally whatever), and it can be whatever let's say: 33.7.56
SPEC_VERSION is the version of the RPC Specification wallet provided, and It can be only one of the versions of the spec let's say: 0.7.1

Now, how do you correlate these two as there is no specification correlation is I guess wallets provide some table on their documentation saying:
API_VERSION SPEC_VERSION
33.7.56 | 0.7.1
33.7.55 | 0.7.1
33.7.53 | 0.7.1
33.7.32 | 0.7.0_ 

2. Fix
_But I think I could do:_
`export type API_VERSION = string;`

_and_ 
```
export interface ApiVersionRequest {
  api_version?: API_VERSION;
}
```

_And avoid using ApiVersion NAME in this case i think all should be ok with naming collision_

**Comment by PhilippeR26** [comment]
Wallet teams are interested to have rather quickly a new version of this lib, including the string types for both versions responses.
